name: Daily Ingest

on:
  workflow_dispatch:    # allows manual runs
  schedule:
    - cron: "0 6 * * *"  # every day at 06:00 UTC

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run ingest pipeline
        run: python ingest.py

      - name: Commit updated data
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/
          git commit -m "Daily ingest $(date +'%Y-%m-%d')"
          git push
